DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS mentors;
DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS student_details;
DROP TABLE IF EXISTS skills;
DROP TABLE IF EXISTS student_skills;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS group_overview;
DROP TABLE IF EXISTS homework;
DROP TABLE IF EXISTS diploma;
DROP TABLE IF EXISTS cert;
DROP TABLE IF EXISTS interview;

