name: CI

on:
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run : |
          echo Sample Workflow