name: ci-3

on:
  push

permissions:
  contents: read

jobs:
  buildTestLint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Build
        run: make build
      - name: Tests
        run: make test
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29