name: CI

on:
  push:
    branches: [ ci-6 ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18	

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.49.0

      - name: Run golangci-lint
        run: golangci-lint run ./... 

      - name: Build
        run :go build -v -o ./cmd/main ./cmd

      - name: Run tests
        run : go test ./... 
